name: flutter_app
description: Mi aplicación Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

  http: ^1.2.2

  flutter_secure_storage: ^9.2.2

  jwt_decoder: ^2.0.1